spring:
  profiles:
    active: dev

  devtools:
    add-properties: false

  datasource:
    url: jdbc:mysql://localhost:3306/archive_db?useSSL=false&serverTimezone=UTC
    username: root
    password: wznazj123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    chat:
      model:
        name: gpt-3.5-turbo
        temperature: 0.7
        max-tokens: 2000
        top-p: 0.9
      system-prompt: |
        你是一个专业的档案管理助手，可以帮助用户：
        1. 查找和检索档案
        2. 回答档案相关问题
        3. 提供档案管理建议
        4. 协助档案借阅流程
      history:
        max-count: 100
        expire-days: 30
      security:
        max-requests-per-minute: 60
        max-tokens-per-day: 100000
      cache:
        enabled: true
        ttl: 3600
        max-size: 1000

  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0

server:
  port: 8080
  servlet:
    context-path: /archive

logging:
  level:
    root: INFO
    com.ray.archive: DEBUG
    org.springframework.security: INFO
    org.springframework.ai: DEBUG
    org.springframework.web: INFO
    org.hibernate: DEBUG

file:
  upload-dir: ./uploads/archives

pdf:
  watermark:
    text: 档案管理系统
    color: "#000000"
    opacity: 0.3
    rotation: 45

jwt:
  secret: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  expiration: 86400000  # 24 hours in milliseconds 