spring:
  datasource:
    url: jdbc:mysql://localhost:3306/archive_db?useSSL=false&serverTimezone=UTC
    username: root
    password: wznazj123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: ./uploads/archives

pdf:
  watermark:
    text: 档案管理系统
    color: "#000000"
    opacity: 0.3
    rotation: 45

jwt:
  secret: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  expiration: 86400000  # 24 hours in milliseconds 